### ISSUE TITLE
United Flarmnet Daily output?

### ISSUE THREAD

**Issue by lordfolken** [Turbo87/united-flarmnet#152]
I see you are building the binary daily. Would it be possible to run it too and provide the output on a stable url?

At least on my system (Debian 11) the binary provided, segfaults instantly.
A stable url i could also integrate directly into https://github.com/XCSoar/xcsoar-data-content/tree/master/data/remote/flarmnet/globe

**Comment by Turbo87** [comment]
> I see you are building the binary daily

not intentionally. it only runs/builds whenever a dependency has been updated.



> Would it be possible to run it too and provide the output on a stable url?

my goal would be to run and publish hourly, but I haven't had time yet to set that up. unfortunately the GitHub Actions cronjobs are not suited for something like this since they would be disabled automatically after a few days due to cryptobros abusing the service 🙄

**Comment by lordfolken** [comment]
Well i'd run daily. I think that would be sufficient. I have also checks for the repository running daily.

**Comment by Turbo87** [comment]
the information that is coming from weglide is updated a lot more often than the rest, which is why I think that hourly could be useful

**Comment by lordfolken** [comment]
Ok i studied the weglide plane pilot association, basically this is very dynamic and can change on a sub daily basis. 
Would an API call be more efficient, than offline data?

**Comment by Turbo87** [comment]
sure, an API call might be better but given the spotty coverage in the air the offline data is still better than nothing. Ideally XCSoar would automatically download the current file on startup.

**Comment by lordfolken** [comment]
Well we do have an update mechanusm now, that shows which files are out of date. 
I would like to start to checksum remote resources and increment the update tag autoatically.
